[localnet]
# number of nodes in the single cluster of the localnet
nodes = 2
# number of seconds to wait for the localnet to come online
localnet_timeout_secs = 60
# MPC backends this MXE supports (default: ["Cerberus"])
# Supported values: "Cerberus"
backends = ["Cerberus"]

[devnet]
# Cluster offset for devnet deployment
# Available options on devnet: 123, 456, 789 (all on Arcium v0.5.1)
cluster_offset = 123
